# -*- coding: utf-8 -*-
"""RockVsMinePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14q2Kh80E2orwJG1x9MevIEMuS2wZmS8W
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""Data Collection and Preprocessing"""

sonar_data = pd.read_csv('/content/sonar data.csv', header=None)

"""look at data there is no header

this will add header 0,1,2....


"""

sonar_data.head()

sonar_data.shape

sonar_data.describe()

sonar_data[60].value_counts()

X = sonar_data.drop(columns=60, axis=1)
Y = sonar_data[60]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, stratify=Y, random_state=1)

"""10 % test data
stratify means 11 Mines (M) and 97 Rocks (R). This is roughly a 53% to 47% split.stratify=Y, train_test_split forces the split to maintain that original ~53% to 47% ratio in both the training set and the test set.

MODEL ---> LR
"""

model = LogisticRegression()

# Train the logistic regression model with training data
model.fit(X_train, Y_train)

"""MODEL EVALUATION"""

# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('Accuracy on training data : ', training_data_accuracy)

# accuracy o test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('accuracy on test data:', test_data_accuracy)

"""the model is working good

MAKING A PREDICTIVE SYSTEM
"""

input_data = (0.0206,0.0132,0.0533,0.0569,0.0647,0.1432,0.1344,0.2041,0.1571,0.1573,0.2327,0.1785,0.1507,0.1916,0.2061,0.2307,0.2360,0.1299,0.3812,0.5858,0.4497,0.4876,1.0000,0.8675,0.4718,0.5341,0.6197,0.7143,0.5605,0.3728,0.2481,0.1921,0.1386,0.3325,0.2883,0.3228,0.2607,0.2040,0.2396,0.1319,0.0683,0.0334,0.0716,0.0976,0.0787,0.0522,0.0500,0.0231,0.0221,0.0144,0.0307,0.0386,0.0147,0.0018,0.0100,0.0096,0.0077,0.0180,0.0109,0.0070)

# changing the imput data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the np array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if(prediction == 'R'):
  print('The object is a rock')
else:
  print('The object is a mine')